import json
import re
from aliyunsdkcore.client import AcsClient
from aliyunsdksas.request.v20181203.DescribeRiskTypeRequest import DescribeRiskTypeRequest
from aliyunsdksas.request.v20181203.ModifyStrategyRequest import ModifyStrategyRequest

client = AcsClient('LTAI5tBsFinWzfYL6eaEc4E4', 'Ye6r0OC7rYx2KWzD2gEDgbKUASC2J4', 'cn-hangzhou')

# request = DescribeRiskTypeRequest()
# request.set_accept_format('json')
# request.set_Lang("en")

# response = client.do_action_with_exception(request)
# responseData = json.loads(response)

# #print(json.dumps(responseData, indent=1))

RiskSubTypeNames="hc_exploit_redis,hc_exploit_activemq,hc_exploit_couchdb,hc_exploit_docker,hc_exploit_es,hc_exploit_hadoop,hc_exploit_influxdb,hc_exploit_jboss,hc_exploit_jenkins,hc_exploit_k8s_api,hc_exploit_ldap,hc_exploit_ldap_linux,hc_exploit_memcache,hc_exploit_mongo,hc_exploit_pgsql,hc_exploit_rabbitmq,hc_exploit_rsync,hc_exploit_zookeeper,hc_docker,hc_middleware_ack_master,hc_middleware_ack_node,hc_middleware_k8s,hc_middleware_k8s_node,hc_suse15_djbh,hc_aliyun_linux3_djbh_l3,hc_aliyun_linux_djbh_l3,hc_anolis8_djbh_l3,hc_bind_djbh,hc_centos6_djbh_l3,hc_centos7_djbh_l3,hc_centos8_djbh_l3,hc_debian_djbh_l3,hc_iis_djbh,hc_informix_djbh,hc_jboss_djbh,hc_mongo_djbh,hc_mssql_djbh,hc_mysql_djbh,hc_nginx_djbh,hc_oracle_djbh,hc_pgsql_djbh,hc_redhat6_djbh_l3,hc_redhat_djbh_l3,hc_redis_djbh,hc_suse10_djbh_l3,hc_suse12_djbh_l3,hc_suse_djbh_l3,hc_ubuntu14_djbh_l3,hc_ubuntu_djbh_l3,hc_was_djbh,hc_weblogic_djbh,hc_win2008_djbh_l3,hc_win2012_djbh_l3,hc_win2016_djbh_l3,hc_aliyun_linux_djbh_l2,hc_centos6_djbh_l2,hc_centos7_djbh_l2,hc_debian_djbh_l2,hc_redhat7_djbh_l2,hc_ubuntu_djbh_l2,hc_win2008_djbh_l2,hc_win2012_djbh_l2,hc_win2016_djbh_l2,hc_aliyun_linux_cis,hc_centos6_cis_rules,hc_centos7_cis_rules,hc_centos8_cis_rules,hc_debian8_cis_rules,hc_ubuntu14_cis_rules,hc_ubuntu16_cis_rules,hc_win2008_cis_rules,hc_win2012_cis_rules,hc_win2016_cis_rules,hc_kylin_djbh_l3,hc_uos_djbh_l3,hc_aliyun_linux,hc_centos6,hc_centos7,hc_debian,hc_redhat6,hc_redhat7,hc_ubuntu,hc_windows_2008,hc_windows_2012,hc_windows_2016,hc_db_mssql,hc_memcached_ali,hc_mongodb,hc_mysql_ali,hc_oracle,hc_pgsql_ali,hc_redis_ali,hc_anolis8_cis,hc_apache,hc_db_couchdb_linux,hc_elasticsearch,hc_hadoop,hc_iis_8,hc_influxdb,hc_jboss_linux,hc_kibana_linux,hc_kylin_cis,hc_middleware_activemq,hc_middleware_jenkins,hc_middleware_rabbitmq,hc_nginx_linux,hc_smb_win,hc_suse15,hc_tomcat_win,hc_uos_cis,tomcat7,hc_mongodb_pwd,hc_weakpwd_ftp_linux,hc_weakpwd_influxdb,hc_weakpwd_jboss,hc_weakpwd_jenkins,hc_weakpwd_linux_sys,hc_weakpwd_mongodb3,hc_weakpwd_mssql,hc_weakpwd_mysql_linux,hc_weakpwd_mysql_win,hc_weakpwd_openldap,hc_weakpwd_openvpn,hc_weakpwd_oracle,hc_weakpwd_pgsql,hc_weakpwd_pptp,hc_weakpwd_proftpd,hc_weakpwd_rabbitmq,hc_weakpwd_redis_linux,hc_weakpwd_rsync,hc_weakpwd_svn,hc_weakpwd_tomcat_linux,hc_weakpwd_vnc,hc_weakpwd_weblogic,hc_weakpwd_win_sys,hc_weak_pwd_activemq,hc_weak_pwd_elastic"

request = ModifyStrategyRequest()
request.set_CycleDays(1)
request.set_RiskSubTypeName("hc_exploit_redis")
request.set_CycleStartTime(0)
request.set_Name("standard-python")

response = client.do_action_with_exception(request)
responseData = json.loads(response)
print(json.dumps(responseData, indent=1))